blank_issues_enabled: false
contact_links:
  - name: Hinbor Backlog
    url: https://github.com/hi-neighbor-est-2022/hinbor-backlog/issues
    about: Initiatives and Epics are tracked in the homebase repo
